# Exercise 2.A Fundamentals of pandas

In [3]:
import numpy as np
import pandas as pd

## Series

In [4]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {'first': 13, 'second': 14, 'third': 15, 'fourth': 16}

In [12]:
ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))  # included list() since the order may change any time; TypeError: 'set' type is unordered, a set is always unordered when series requires a fixed order
ser4 = pd.Series(ad)

print(ser1)
print(ser2)
print(ser3)
print(ser4)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64
first     13
second    14
third     15
fourth    16
dtype: int64

In [15]:
# ser5 = pd.Series(17, 18, 19, 20)  #TypeError: Index(...) must be called with a collection of some kind, 18 was passed; the argument needs to be a collection, like a list, tuple, or dictionary, before being passed through

## DataFrames from Series

In [26]:
df1 = pd.DataFrame(ser1)
df1

   0
0  1
1  2
2  3
3  4

In [27]:
df1.insert(1, "ser2", ser2)
df1.insert(2, "ser3", ser3)
df1

   0  ser2  ser3
0  1     5     9
1  2     6    10
2  3     7    11
3  4     8    12

In [28]:
df1.insert(3, "ser4", ser4)
df1  # when ser4 was added, it automatically assumed that ser4 was going to be numbers too. Since this is not the case, it shows up as NaN; pandas matches values by indexes, which means that it couldn't find the value (0 != first)

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN

In [30]:
df1.loc[4] = [5, 9, 12, 0]
df1

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0

## Reading Data into a DataFrame

In [ ]:
df2.read_csv