# Exercise 2.B Cleaning up data

In [21]:
import numpy as np
import pandas as pd

In [22]:
df = pd.read_csv("test_data.csv")

In [23]:
df.describe()

       Unnamed: 0       ID       Age      Score
count     8.00000  8.00000   6.00000   7.000000
mean      3.50000  4.50000  25.00000  66.285714
std       2.44949  2.44949   6.78233  32.576650
min       0.00000  1.00000  18.00000  -1.000000
25%       1.75000  2.75000  19.75000  60.000000
50%       3.50000  4.50000  23.50000  78.000000
75%       5.25000  6.25000  29.50000  87.500000
max       7.00000  8.00000  35.00000  92.000000

## Filtering a DataFrame

In [24]:
df[df["Age"] > 18]

   Unnamed: 0  ID     Name   Age     City  Score
0           0   1   Alicia  25.0       NY   85.0
2           2   3  Charlie  22.0  Chicago   -1.0
3           3   4  Dominic  19.0  Houston   65.0
4           4   5      Eve  31.0  Phoenix   78.0
5           5   6    Frank  35.0   Boston    NaN

In [25]:
# df[(df["Score"] > 50) & (df["Score"] < 100)]
df[df["Score"].between(50, 100)]

   Unnamed: 0  ID     Name   Age       City  Score
0           0   1   Alicia  25.0         NY   85.0
1           1   2      Bob   NaN         LA   92.0
3           3   4  Dominic  19.0    Houston   65.0
4           4   5      Eve  31.0    Phoenix   78.0
6           6   7    Grace   NaN     Austin   55.0
7           7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [26]:
df_cleaned = df.drop(df[df["Score"] < 0].index)
df_cleaned

   Unnamed: 0  ID     Name   Age       City  Score
0           0   1   Alicia  25.0         NY   85.0
1           1   2      Bob   NaN         LA   92.0
3           3   4  Dominic  19.0    Houston   65.0
4           4   5      Eve  31.0    Phoenix   78.0
5           5   6    Frank  35.0     Boston    NaN
6           6   7    Grace   NaN     Austin   55.0
7           7   8    Heidi  18.0  San Diego   90.0

In [27]:
df_cleaned = df_cleaned.drop(columns=["City"])
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob   NaN   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace   NaN   55.0
7           7   8    Heidi  18.0   90.0

In [28]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

In [29]:
df_cleaned["Score"] = df_cleaned["Score"].replace(0, df_cleaned["Score"].mean())
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

In [30]:
df_cleaned = df_cleaned.dropna()
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

In [31]:
df_cleaned = df_cleaned.set_index("ID")
df_cleaned

    Unnamed: 0     Name   Age  Score
ID
1            0   Alicia  25.0   85.0
2            1      Bob  25.6   92.0
4            3  Dominic  19.0   65.0
5            4      Eve  31.0   78.0
7            6    Grace  25.6   55.0
8            7    Heidi  18.0   90.0