# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
    'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}
df_sales = pd.DataFrame(data)

In [3]:
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Price"]

In [5]:
print(f"Total units sold: {df_sales["Units_Sold"].sum()}")
print(f"Total revenue: {df_sales["Revenue"].sum()}")

Total units sold: 105
Total revenue: 16000

In [8]:
print(f"Average units sold: {df_sales["Units_Sold"].mean()}")
print(f"Average revenue: {df_sales["Revenue"].mean()}")

Average units sold: 11.666666666666666
Average revenue: 1777.7777777777778

## Grouping Data

In [11]:
print(df_sales.groupby("Product")["Units_Sold"].sum())
print(df_sales.groupby("Product")["Revenue"].sum())

Product
A    25
B    30
C    50
Name: Units_Sold, dtype: int64
Product
A    2500
B    6000
C    7500
Name: Revenue, dtype: int64

In [12]:
print(df_sales.groupby("Region")["Units_Sold"].mean())
print(df_sales.groupby("Region")["Revenue"].mean())

Region
East     15.000000
North    11.666667
South    15.000000
West      5.000000
Name: Units_Sold, dtype: float64
Region
East     2000.0
North    1750.0
South    2625.0
West      750.0
Name: Revenue, dtype: float64

In [26]:
print(df_sales.groupby(["Product", "Region"])["Units_Sold"].sum())
print(df_sales.groupby(["Product", "Region"])["Revenue"].sum())

Product  Region
A        East      10
         North     10
         West       5
B        North     10
         South     15
         West       5
C        East      20
         North     15
         South     15
Name: Units_Sold, dtype: int64
Product  Region
A        East      1000
         North     1000
         West       500
B        North     2000
         South     3000
         West      1000
C        East      3000
         North     2250
         South     2250
Name: Revenue, dtype: int64

## Sorting and Ranking Data

In [15]:
df_sales.sort_values(by="Units_Sold", ascending=True)

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [16]:
df_sales.sort_values(by="Revenue", ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [17]:
df_sales["Revenue_Rank"] = df_sales["Revenue"].rank(ascending=False)

In [18]:
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [19]:
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)

In [21]:
df_merged = pd.merge(df_sales, df_products, on="Product")

In [22]:
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [27]:
print(df_merged.groupby("Category")["Revenue"].sum())

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64